update freight quote
kynttt/POSEIDONFREIGHTBROKERV1 pull request #107
Opened 2024-07-19 04:09 UTC by KennethKnows

freight quote enhance

2024-07-19 08:54 UTC, kynttt requested changes
no right margin

2024-07-22 06:05 UTC, KennethKnows commented
Apply margin already sir

2024-07-22 09:34 UTC, kynttt requested changes
![freight quote](https://github.com/user-attachments/assets/352f6730-f828-4f13-91c1-8fa322ffab0c)
This is in my laptop view. fix x-axis margin or padding

2024-07-23 06:00 UTC, KennethKnows commented
Nag update ko new sir, try to check po

2024-07-25 02:20 UTC, closed without merging