enhance features
kynttt/POSEIDONFREIGHTBROKERV1 pull request #108
Opened 2024-07-19 07:58 UTC by KennethKnows

Enhance features

2024-07-19 09:16 UTC, kynttt requested changes
the image section and the texts section should not take up same proportion of space from their parent component based on the design. Text section occupies more space from the parent.

2024-07-23 08:58 UTC, KennethKnows commented
Update features - please check

2024-07-24 01:23 UTC, KennethKnows commented
Update features - please check 07/24/2024

2024-07-25 02:35 UTC, kynttt commented
merge with update

2024-07-25 02:35 UTC, merged